import type { DrinkMix, GelOrSolid } from '../types';

export const DEFAULT_DRINK_MIXES: DrinkMix[] = [
  {
    id: 'pf-carb-electrolyte',
    name: 'PF Carb & Electrolyte Mix',
    carbsPerScoop: 15,
    sodiumPerScoop: 200,
    caffeinePerScoop: 0,
    caloriesPerScoop: 60,
    isDefault: true,
  },
  {
    id: 'gatorade-thirst-quencher',
    name: 'Gatorade Thirst Quencher',
    carbsPerScoop: 22,
    sodiumPerScoop: 300,
    caffeinePerScoop: 0,
    caloriesPerScoop: 90,
    isDefault: true,
  },
  {
    id: 'skratch-labs',
    name: 'Skratch Labs',
    carbsPerScoop: 19,
    sodiumPerScoop: 380,
    caffeinePerScoop: 0,
    caloriesPerScoop: 80,
    isDefault: true,
  },
  {
    id: 'maurten-320',
    name: 'Maurten Drink Mix 320',
    carbsPerScoop: 80,
    sodiumPerScoop: 180,
    caffeinePerScoop: 0,
    caloriesPerScoop: 320,
    isDefault: true,
  },
  {
    id: 'sis-beta-fuel',
    name: 'SIS Beta Fuel',
    carbsPerScoop: 40,
    sodiumPerScoop: 250,
    caffeinePerScoop: 0,
    caloriesPerScoop: 160,
    isDefault: true,
  },
];

export const DEFAULT_SOLIDS: GelOrSolid[] = [
  {
    id: 'pf-30-chew',
    name: 'PF 30 Chew (1 packet)',
    type: 'chew',
    carbsPerServing: 30,
    sodiumPerServing: 80,
    caffeinePerServing: 0,
    caloriesPerServing: 120,
    servingDescription: '1 packet',
    isDefault: true,
  },
  {
    id: 'haribo-gummies',
    name: 'Haribo Gummies (13 pcs)',
    type: 'gummy',
    carbsPerServing: 31,
    sodiumPerServing: 10,
    caffeinePerServing: 0,
    caloriesPerServing: 130,
    servingDescription: '13 pieces',
    isDefault: true,
  },
  {
    id: 'maurten-gel-100',
    name: 'Maurten Gel 100',
    type: 'gel',
    carbsPerServing: 25,
    sodiumPerServing: 35,
    caffeinePerServing: 0,
    caloriesPerServing: 100,
    servingDescription: '1 packet',
    isDefault: true,
  },
  {
    id: 'sis-go-gel',
    name: 'SIS Go Isotonic Gel',
    type: 'gel',
    carbsPerServing: 22,
    sodiumPerServing: 20,
    caffeinePerServing: 0,
    caloriesPerServing: 87,
    servingDescription: '1 packet',
    isDefault: true,
  },
  {
    id: 'clif-bloks',
    name: 'Clif Bloks (3 chews)',
    type: 'chew',
    carbsPerServing: 24,
    sodiumPerServing: 70,
    caffeinePerServing: 0,
    caloriesPerServing: 100,
    servingDescription: '3 chews',
    isDefault: true,
  },
  {
    id: 'sis-caffeine-gel',
    name: 'SIS Go + Caffeine Gel',
    type: 'gel',
    carbsPerServing: 22,
    sodiumPerServing: 20,
    caffeinePerServing: 75,
    caloriesPerServing: 87,
    servingDescription: '1 packet',
    isDefault: true,
  },
];
